### ISSUE TITLE
Add a link back to repo

### ISSUE THREAD

**Issue by Atinux** [bdrtsky/new-fetch-example#2]
When navigating on https://xr8nr.sse.codesandbox.io, it would be nice to have a link back to this repo.

Might be added in the footer or via a Ribbon (like https://simonwhitaker.github.io/github-fork-ribbon-css/)

**Comment by bdrtsky** [comment]
I've added http://tholman.com/github-corners/

Now thinking, should I also put Codesandbox link, or this will be too much?

**Comment by Atinux** [comment]
Updated the README for adding the CodeSandBox button :)
